# Workflow name
name: Release process

on:
  # Events
  push:
    branches:
      - master

jobs:
  # Jobs
  generate-release:
    name: Create Github Release
    # Runner OS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Actions
        uses: actions/checkout@v2
      - name: Node installation
        # Actions
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm install
